# Site settings
title: Darshan Soni
email: hello@darshandsoni.com
description: > # this means to ignore newlines until "baseurl:"
  Integrated Engineering student interested in transportation systems.
  Hobbyist front end web developer. Enthusiast of all things Design.
baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://darshandsoni.com" # the base hostname & protocol for your site
twitter_username: darshandsoni
github_username:  darshandsoni
# Build settings
markdown: kramdown
500px_consumer_key_file: 500px-consumer-key

gems:
  - jekyll-minifier

jekyll-minifier:
  exclude: sitemap.xml

# HTTPS pointing for search engines
url: https://darshandsoni.com
enforce_ssl: darshandsoni.com

#flickr:
#    cache_dir: ./_cache/flickr
#    api_key:  349f2e154f66eac6d552d2fc74211c00
#    shared_secret: d611e66056b44292
#    access_token: 72157664005092346-5728d65756e448c5
#    access_secret: e332fc088464f248
